class LLMServiceError(Exception): ...


class LLMConfigurationError(LLMServiceError): ...


class FieldAlreadyPopulatedError(LLMServiceError): ...


class ModelOutputError(LLMServiceError): ...


class AzureResponsesError(LLMServiceError): ...
