services:
  api:
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./deployments/api/src:/app/deployments/api/src
      - ./packages:/app/packages
    command:
      - uvicorn
      - stitch.api.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/deployments/api/src
      - --reload-dir
      - /app/packages
      - --reload-exclude
      - "*/tests/*"
  localauth0:
    profiles: [auth-test]
    image: public.ecr.aws/primaassicurazioni/localauth0:0.8.3
    healthcheck:
      test: ["CMD", "/localauth0", "healthcheck"]
      start_period: 10s
      start_interval: 1s
      interval: 30s
    environment:
      LOCALAUTH0_CONFIG_PATH: /etc/localauth0.toml
    volumes:
      - ./dev/localauth0.toml:/etc/localauth0.toml:ro
  auth0-proxy:
    profiles: [auth-test]
    image: openresty/openresty:alpine
    ports:
      - "3100:80"
    volumes:
      - ./dev/localauth0-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      localauth0:
        condition: service_healthy
