[project]
name = "stitch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

[tool.uv.workspace]
members = [
  "deployments/api",
  "deployments/entity-linkage",
  "deployments/stitch-llm",
  "packages/stitch-auth",
  "packages/stitch-client",
  "packages/stitch-models",
  "packages/stitch-observability",
  "packages/stitch-ogsi",
]

[tool.uv.sources]
stitch-auth = { workspace = true }
stitch-client = { workspace = true }

[dependency-groups]
dev = ["pytest>=8.4.2", "ruff>=0.14.2"]
