"""baseline

Revision ID: 6de2b873bacb
Revises:
Create Date: 2026-06-04 12:35:31.176312
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6de2b873bacb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "og_field_source_priority",
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("source"),
        sa.UniqueConstraint("priority"),
    )
    op.bulk_insert(
        sa.table(
            "og_field_source_priority",
            sa.column("source", sa.String),
            sa.column("priority", sa.Integer),
        ),
        [
            {"source": "rmi", "priority": 1},
            {"source": "wm", "priority": 2},
            {"source": "gem", "priority": 3},
            {"source": "llm", "priority": 4},
        ],
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub", name="uq_users_sub"),
    )
    op.create_index(op.f("ix_users_sub"), "users", ["sub"], unique=False)
    op.create_table(
        "og_field_resources",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "repointed_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repointed_id"],
            ["og_field_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "rp_repointed_id_idx", "og_field_resources", ["repointed_id"], unique=False
    )
    op.create_table(
        "oil_gas_field_sources",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("gem", "wm", "rmi", "llm", native_enum=False),
            nullable=False,
        ),
        sa.Column("owners", sa.JSON(), nullable=True),
        sa.Column("operators", sa.JSON(), nullable=True),
        sa.Column("source_record", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("name_local", sa.String(), nullable=True),
        sa.Column("state_province", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("basin", sa.String(), nullable=True),
        sa.Column("reservoir_formation", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("discovery_year", sa.Integer(), nullable=True),
        sa.Column("production_start_year", sa.Integer(), nullable=True),
        sa.Column("fid_year", sa.Integer(), nullable=True),
        sa.Column(
            "location_type",
            sa.Enum("Onshore", "Offshore", "Unknown", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "production_conventionality",
            sa.Enum(
                "Conventional", "Unconventional", "Mixed", "Unknown", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column(
            "primary_hydrocarbon_group",
            sa.Enum(
                "Ultra-Light Oil",
                "Light Oil",
                "Medium Oil",
                "Heavy Oil",
                "Extra-Heavy Oil",
                "Dry Gas",
                "Wet Gas",
                "Acid Gas",
                "Condensate",
                "Mixed",
                "Unknown",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "field_status",
            sa.Enum(
                "Producing", "Non-Producing", "Abandoned", "Planned", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merge_candidates",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("fingerprint", sa.String(length=255), nullable=False),
        sa.Column("review_notes", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "merged_resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merged_resource_id"],
            ["og_field_resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uc_merge_candidate_fingerprint"),
    )
    op.create_table(
        "og_field_memberships",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column(
            "source_pk",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "INVALID", name="membershipstatus"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["og_field_resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source"],
            ["og_field_source_priority.source"],
        ),
        sa.ForeignKeyConstraint(
            ["source_pk"],
            ["oil_gas_field_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merge_candidate_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "merge_candidate_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merge_candidate_id"],
            ["merge_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["og_field_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "merge_candidate_id", "resource_id", name="uc_merge_candidate_resource_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError(f"Irreversible migration: {revision}")
