"""baseline

Revision ID: f3fb36006ce6
Revises:
Create Date: 2026-06-17 19:08:25.103926
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import stitch.api.db.model.types

# revision identifiers, used by Alembic.
revision = "f3fb36006ce6"
down_revision = None
branch_labels = None
depends_on = None

DEFAULT_PRIORITIES = [
    {"source": "rmi", "priority": 1},
    {"source": "gem", "priority": 2},
    {"source": "wm", "priority": 3},
    {"source": "llm", "priority": 4},
]

# Attributes that are free-text and worth a substring (ILIKE) index.
_TRGM_COLNAMES = ("name", "name_local", "basin", "state_province", "region")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "og_field_source_priority",
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("source"),
        sa.UniqueConstraint("priority"),
    )
    op.bulk_insert(
        sa.table(
            "og_field_source_priority",
            sa.column("source", sa.String),
            sa.column("priority", sa.Integer),
        ),
        DEFAULT_PRIORITIES,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub", name="uq_users_sub"),
    )
    op.create_index(op.f("ix_users_sub"), "users", ["sub"], unique=False)
    op.create_table(
        "og_field_resources",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "repointed_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repointed_id"],
            ["og_field_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "rp_repointed_id_idx", "og_field_resources", ["repointed_id"], unique=False
    )
    op.create_table(
        "oil_gas_field_sources",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("gem", "wm", "rmi", "llm", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "source_record", stitch.api.db.model.types.StitchJson(), nullable=False
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merge_candidates",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("fingerprint", sa.String(length=255), nullable=False),
        sa.Column("review_notes", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "merged_resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merged_resource_id"],
            ["og_field_resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uc_merge_candidate_fingerprint"),
    )
    op.create_table(
        "og_field_memberships",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column(
            "source_pk",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "INVALID", name="membershipstatus"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("last_updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["og_field_resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source"],
            ["og_field_source_priority.source"],
        ),
        sa.ForeignKeyConstraint(
            ["source_pk"],
            ["oil_gas_field_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "og_field_resource_source_priority",
        sa.Column(
            "resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["og_field_resources.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source"],
            ["og_field_source_priority.source"],
        ),
        sa.PrimaryKeyConstraint("resource_id", "source"),
    )
    op.create_table(
        "oil_gas_field_source_values",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "source_pk",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("colname", sa.String(length=50), nullable=False),
        sa.Column("value_text", sa.String(), nullable=True),
        sa.Column(
            "value_num",
            sa.Float().with_variant(sa.DOUBLE_PRECISION(), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "value_json",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.CheckConstraint(
            "colname IN ('name', 'country', 'name_local', 'state_province', 'region', 'basin', 'reservoir_formation', 'location_type', 'production_conventionality', 'primary_hydrocarbon_group', 'field_status', 'latitude', 'longitude', 'discovery_year', 'production_start_year', 'fid_year', 'owners', 'operators')",
            name="ck_source_value_colname",
        ),
        sa.CheckConstraint(
            "(CASE WHEN value_text IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN value_num IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN value_json IS NOT NULL THEN 1 ELSE 0 END) = 1",
            name="ck_source_value_exactly_one",
        ),
        sa.ForeignKeyConstraint(
            ["source_pk"], ["oil_gas_field_sources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_pk", "colname", name="uq_source_value_colname"),
    )
    op.create_index(
        "ix_source_value_colname_num",
        "oil_gas_field_source_values",
        ["colname", "value_num"],
        unique=False,
    )
    op.create_index(
        "ix_source_value_colname_text",
        "oil_gas_field_source_values",
        ["colname", "value_text"],
        unique=False,
    )
    op.create_table(
        "merge_candidate_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "merge_candidate_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "resource_id",
            sa.BigInteger()
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merge_candidate_id"],
            ["merge_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["og_field_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "merge_candidate_id", "resource_id", name="uc_merge_candidate_resource_id"
        ),
    )
    # ### end Alembic commands ###

    # Postgres-only: trigram GIN index for ILIKE substring search over the
    # free-text attributes. Partial, so it only covers the searchable colnames.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        colname_list = ", ".join(f"'{c}'" for c in _TRGM_COLNAMES)
        op.create_index(
            "ix_source_value_value_text_trgm",
            "oil_gas_field_source_values",
            ["value_text"],
            unique=False,
            postgresql_using="gin",
            postgresql_ops={"value_text": "gin_trgm_ops"},
            postgresql_where=sa.text(f"colname IN ({colname_list})"),
        )


def downgrade() -> None:
    raise RuntimeError(f"Irreversible migration: {revision}")
