from sqlalchemy.orm import Session


def create(session: Session): ...


def get(session: Session): ...


def get_all_resources(session: Session): ...


def get_all_roots(session: Session): ...


def merge_resources(session: Session): ...


def unmerge_resourcs(session: Session): ...


def unify_resources(session: Session): ...


def repoint_resource(session: Session): ...
